# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f574cd9647c0a5030fab201521e68cbf3537f13b0bf6c86d590d3fddae2b66fa5e3de4b0a3acc196cd52ce4e5ea347b26fa1d6b4e7e06149c42111d193e7ca2

test:
  secret_key_base: 64980643c32808093738524d5555707a41312333a3223322ab2deb4c70d1dc56d0ad5fd33871ef01241c5ba778e815c165456dc892741ef1cfa33b3b7fe23541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
